<template>
<div class="content">
	<div class="container-fluid">
	<h3 class="card-title">Community Fund</h3>
	
<h3 class="ui violet header">Why was the NavCoin Community Fund created?</h3>

<p>NavCoin is a decentralised project, which relies on the efforts of individuals all over the world to secure, maintain and grow its network. The NavCoin Community Fund aims to help strengthen the network by encouraging and incentivising more people to get involved.</p>

<h3 class="ui violet header">The world’s first decentralised dual-vote fund</h3>
<p>The NavCoin Community Fund is different to other development funds for two key reasons:
    It’s fully decentralised, meaning it’s not controlled or managed by any individual or single group.
    Projects are approved for funding and payment using a unique two-stage voting process. This ensures that people only get paid if they deliver what they promised in their proposal.
</p>
<img class="ui huge bordered image rounded" src="static/img/cfund-3-step.jpg">
<h3 class="ui violet header">Technical details</h3>
<p>For a more technical explanation of the science behind the NavCoin Community Fund, check out this paper by NavCoin Core developer Alex Vazquez on GitHub: https://github.com/aguycalled/cfundpaper/blob/master/cfund.pdf</p>
</p>

<h3 class="ui violet header">Frequently Asked Questions</h3>
<p class="ui header">How are funds generated?
<p>
Funds are generated by the network at the rate of 0.25 NAV per block. This amount was made available after a network consensus vote in early 2018 that decreased staking rewards from 5 to 4% pa. It equates to 250,000 NAV per year. Note: There is a NPIP to increase this amount - the rationale why can be seen in this thread on reddit.</p>
</p>

<p class="ui header">Where do I create a proposal?</p>
<p>To start with, there will be a proposal form that generates a piece of code which you then paste into your wallet.<br/> In this form you will need to include the following details:<br/><br/>
    The title of your project<br/>
    Description (ideally a link to a full description)<br/>
    The amount of funding you want<br/>
    Your wallet address<br/>
    How long it will take to complete - consider giving yourself longer than you expect<br/>
</p>
<p class="ui header">How do I vote?
<p>To vote you must be actively staking NavCoin. Votes are cast from within your wallet - and each time you stake you will ‘cast a vote’ to the network. Then at the end of each voting period (roughly a week) the votes are tallied up.</p>
</p>

<p class="ui header">What types of projects can be submitted?
<p>There is no restriction on the type of project you can submit. However it should be thought through properly and be something you think the NavCoin network might realistically support. It could be to develop an application that expands the NavCoin ecosystem, or something unrelated like a donation to charity. It’s entirely up to you.</p>
</p>

<p class="ui header">What does it cost to make a proposal?
<p>The minimum submission fee is 100 NAV, however you can elect to pay a higher fee. The fees go into the Community Fund. The benefit of paying a higher fee is that it can help you proposal receive funding first. For example if two projects are accepted, the one paying the higher fee will get its funding before the other. Also worth noting that you can add your submission fee as an extra cost in your proposal if you wish, to receive the money back.</p>
</p>

<p class="ui header">How long will it take to go through voting/approval process?
<p>It depends on how well your project is received once you’ve submitted it to the blockchain for voting. It could take as little as one block period (about seven days). For a project to be accepted at least 50% of NavCoin stakers must participate in the vote, and 75% of them must vote YES. If 67.5% vote NO the proposal is rejected. The maximum time a project has to reach the 50% quorum is six block periods.</p>
</p>

<p class="ui header">Can I split payment requests?
<p>Yes you can. In fact, splitting up your work into sections with a planned series of payment requests would be an ideal option. For example, if you want to make a video you could make the first payment request for the script, the second for the storyboards, and the final for the finished video. This approach means your project could benefit from regular feedback, which can help you solve problems early on and make delivering the finished project easier.</p>
</p>

<p class="ui header">How much can I apply for?
<p>The amount of funds you request should be a realistic estimate of the cost of completing your project successfully. However there is no limit on how much NAV a proposal can ask for. But if the proposal is accepted by the community and there are not enough NAV in the Community Fund at the time, then the proposal enters an ‘accepted but waiting for funds’ state. Then once there are enough NAV in the fund, the proposal will be given the go ahead and the NAV to pay for it will be locked away to be used for payment request for that proposal when it’s finished.</p>
</p>

<p class="ui header">Where should I post/talk about my project?
<p>The NavCoin Community Collab Forum (launching soon) is a purpose built forum for submitting your proposal and discussing it with other NavCoin community members. You can ask for advice, and find people to add expertise to your team. You can also use the existing NavCoin channels on Discord, Reddit and Telegram.</p>
</p>

<p class="ui header">What can I do to help my proposal get votes?
<p>You need to convince NavCoin stakers that your project deserves a share of the network’s funds. To do that you need to clearly and concisely express the value it brings to the Navcoin ecosystem, or to the world as a whole. You’re free to promote your proposal to NavCoin stakers however you want, but the Collab forum, Discord and Reddit are good places to start.</p>
</p>
</div>
</div>
</template>